name: Compile dhall
on: [push, pull_request]
jobs:
  compile-upkeep-dhall:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v16
      - uses: actions/checkout@v2
      - run: nix-shell --run "./generate.sh"
      - run: git diff --exit-code
