name: upkeep

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh

      - name: Checkout nixpkgs-upkeep
        uses: actions/checkout@v2
        with:
          path: nixpkgs-upkeep

      - name: Checkout nixpkgs
        uses: actions/checkout@v2
        with:
          repository: NixOS/nixpkgs
          path: nixpkgs
          token: ${{ secrets.GH_TOKEN }}
          # 0 means get everything. See https://github.community/t/automating-push-to-public-repo/17742/11?u=samuela
          fetch-depth: 0

      - name: Run custom update-script
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          cp nixpkgs-upkeep/custom-updaters/update-vscode.sh nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh
          ./nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh
          rm nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh

      - working-directory: ./nixpkgs
        run: git diff

      - name: Create PR
        working-directory: ./nixpkgs
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          GH_TOKEN=$GH_TOKEN ./../nixpkgs-upkeep/create-pr.sh vscode
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
