name: upkeep

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches: [main]

jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v10

      - name: Checkout nixpkgs-upkeep
        uses: actions/checkout@v2
        with:
          path: nixpkgs-upkeep

      - name: Checkout nixpkgs
        uses: actions/checkout@v2
        with:
          repository: NixOS/nixpkgs
          path: nixpkgs
          token: ${{ secrets.GH_TOKEN }}

      - name: Check current package version
        working-directory: ./nixpkgs
        run: |
          PACKAGE="vscode"
          CURRENT_VERSION="$(nix eval --raw -f . $PACKAGE.version)"
          echo "::set-env name=PACKAGE::$PACKAGE"
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"

      - name: Run custom update-script
        run: |
          cp nixpkgs-upkeep/custom-updaters/update-vscode.sh nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh
          ./nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh
          rm nixpkgs/pkgs/applications/editors/vscode/update-vscode.sh

      - working-directory: ./nixpkgs
        run: git diff

      - name: Create PR
        working-directory: ./nixpkgs
        run: |
          echo $GITHUB_RUN_NUMBER
          GH_TOKEN=$GH_TOKEN \
            PACKAGE=$PACKAGE \
            CURRENT_VERSION=$CURRENT_VERSION \
            GITHUB_WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            ./../nixpkgs-upkeep/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  vscodium:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v10

      - name: Checkout nixpkgs-upkeep
        uses: actions/checkout@v2
        with:
          path: nixpkgs-upkeep

      - name: Checkout nixpkgs
        uses: actions/checkout@v2
        with:
          repository: NixOS/nixpkgs
          path: nixpkgs
          token: ${{ secrets.GH_TOKEN }}

      - name: Check current package version
        working-directory: ./nixpkgs
        run: |
          PACKAGE="vscodium"
          CURRENT_VERSION="$(nix eval --raw -f . $PACKAGE.version)"
          echo "::set-env name=PACKAGE::$PACKAGE"
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"

      - name: Run custom update-script
        run: |
          cp nixpkgs-upkeep/custom-updaters/update-vscodium.sh nixpkgs/pkgs/applications/editors/vscode/update-vscodium.sh
          ./nixpkgs/pkgs/applications/editors/vscode/update-vscodium.sh
          rm nixpkgs/pkgs/applications/editors/vscode/update-vscodium.sh

      - working-directory: ./nixpkgs
        run: git diff

      - name: Create PR
        working-directory: ./nixpkgs
        run: GH_TOKEN=$GH_TOKEN PACKAGE=$PACKAGE CURRENT_VERSION=$CURRENT_VERSION ./../nixpkgs-upkeep/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
