name: upkeep

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh

      - name: Checkout nixpkgs-upkeep
        uses: actions/checkout@v2
        with:
          path: nixpkgs-upkeep

      - name: Checkout nixpkgs
        uses: actions/checkout@v2
        with:
          repository: NixOS/nixpkgs
          path: nixpkgs

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          cd nixpkgs/pkgs/applications/editors/vscode
          ./update.sh || true
          git diff
          git add .
          git commit -m "Update VSCode"
          git push

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd
          ls
      - run: ls nixpkgs-upkeep
      - run: ls nixpkgs
